// <auto-generated />
using System;
using FavouriteMonstersAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FavouriteMonstersAPI.Migrations
{
    [DbContext(typeof(MonstersDbContext))]
    [Migration("20220819003040_added token table")]
    partial class addedtokentable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FavouriteMonstersAPI.Models.Elements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Elements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9d30873-4156-4622-bb5f-166b1376667a"),
                            Color = "#cf3b47",
                            Name = "Fire"
                        },
                        new
                        {
                            Id = new Guid("3e202ada-0856-4df8-b8ec-6b772e1adc9a"),
                            Color = "#4f6cd0",
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("63839322-9678-47aa-9e4c-dc64f2b05e14"),
                            Color = "#5d7a28",
                            Name = "Grass"
                        });
                });

            modelBuilder.Entity("FavouriteMonstersAPI.Models.Monsters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("FavouriteMonstersAPI.TokenAuthentication.Token", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Value");

                    b.ToTable("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
